/**
 * Demo Data Module — COACHFLO Coaching Console
 * Generates realistic sample data for the demo experience
 */

import type { Client, Session, ClientGoal, ClientNote } from './types';

// ─── Demo Client Data ───
export const DEMO_CLIENTS: Client[] = [
  {
    id: 'demo-1',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Rina Sari',
    email: 'rina@email.com',
    whatsapp: '+62812345001',
    status: 'active',
    phase: 'Intake',
    goal: 'Manifestasi kebebasan finansial Rp 100 juta/bulan',
    bio: 'Seorang ibu muda yang ingin mewujudkan kebebasan finansial melalui bisnis online dan investasi. Saat ini bekerja sebagai karyawan swasta dengan penghasilan Rp 12 juta/bulan.',
    tags: ['finansial', 'bisnis', 'manifestasi'],
    progress: 15,
    totalSessions: 3,
    nextSession: '2026-06-02T10:00:00Z',
    lastSessionAt: '2026-05-25T10:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2026-05-01T08:00:00Z',
    updatedAt: '2026-05-25T10:00:00Z',
  },
  {
    id: 'demo-2',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Budi Hartono',
    email: 'budi@email.com',
    whatsapp: '+62812345002',
    status: 'active',
    phase: 'Self-Concept',
    goal: 'Menarik hubungan cinta yang sehat dan kompatibel',
    bio: 'Pria 32 tahun yang sudah 3 tahun menjomblo. Punya limiting belief bahwa dia tidak cukup baik untuk dicintai. Ingin membangun self-love terlebih dahulu.',
    tags: ['hubungan', 'self-love', 'manifestasi'],
    progress: 35,
    totalSessions: 6,
    nextSession: '2026-06-01T14:00:00Z',
    lastSessionAt: '2026-05-28T14:00:00Z',
    goalFocusArea: 'Pasangan',
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-05-28T14:00:00Z',
  },
  {
    id: 'demo-3',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Maya Putri',
    email: 'maya@email.com',
    whatsapp: '+62812345003',
    status: 'active',
    phase: 'SATS',
    goal: 'Manifestasi promosi menjadi Head of Department',
    bio: 'Wanita karir yang bekerja di perusahaan multinasional. Sudah 5 tahun di posisi yang sama dan merasa siap naik level. Percaya diri tapi ingin mempercepat prosesnya.',
    tags: ['karir', 'promosi', 'SATS'],
    progress: 55,
    totalSessions: 9,
    nextSession: '2026-06-03T09:00:00Z',
    lastSessionAt: '2026-05-27T09:00:00Z',
    goalFocusArea: 'Karir',
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-05-27T09:00:00Z',
  },
  {
    id: 'demo-4',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Andi Wijaya',
    email: 'andi@email.com',
    whatsapp: '+62812345004',
    status: 'active',
    phase: 'Living End',
    goal: 'Menarik kesehatan optimal dan tubuh ideal 70kg',
    bio: 'Pria 38 tahun yang ingin menurunkan berat badan dari 90kg ke 70kg. Sudah coba berbagai diet tapi selalu gagal. Ingin mengubah mindset tentang tubuh dan kesehatan.',
    tags: ['kesehatan', 'tubuh-ideal', 'living-end'],
    progress: 75,
    totalSessions: 12,
    nextSession: '2026-06-04T11:00:00Z',
    lastSessionAt: '2026-05-29T11:00:00Z',
    goalFocusArea: 'Kesehatan',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-05-29T11:00:00Z',
  },
  {
    id: 'demo-5',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Siti Rahma',
    email: 'siti@email.com',
    whatsapp: '+62812345005',
    status: 'active',
    phase: 'Progress',
    goal: 'Manifestasi bisnis bakery dengan omzet Rp 50 juta/bulan',
    bio: 'Ibu rumah tangga yang punya passion baking. Sudah mulai jualan dari rumah dengan omzet Rp 5 juta/bulan. Ingin scale up dan buka toko proper.',
    tags: ['bisnis', 'bakery', 'manifestasi'],
    progress: 85,
    totalSessions: 15,
    nextSession: '2026-06-05T15:00:00Z',
    lastSessionAt: '2026-05-30T15:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-05-30T15:00:00Z',
  },
  {
    id: 'demo-6',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Dewi Lestari',
    email: 'dewi@email.com',
    whatsapp: '+62812345006',
    status: 'active',
    phase: 'Intake',
    goal: 'Menarik kehidupan yang lebih spiritual dan damai',
    bio: 'Wanita 28 tahun yang merasa kehilangan arah. Ingin membangun koneksi yang lebih dalam dengan dirinya sendiri dan alam semesta.',
    tags: ['spiritual', 'inner-peace', 'manifestasi'],
    progress: 10,
    totalSessions: 2,
    nextSession: '2026-06-06T13:00:00Z',
    lastSessionAt: '2026-05-22T13:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-05-22T13:00:00Z',
  },
  {
    id: 'demo-7',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Raka Pratama',
    email: 'raka@email.com',
    whatsapp: '+62812345007',
    status: 'active',
    phase: 'Self-Concept',
    goal: 'Menarik pasangan yang supportive dan ambitious',
    bio: 'Pria 30 tahun, entrepreneur sukses tapi kesepian. Ingin menemukan pasangan yang memahami gaya hidupnya dan mendukung visinya.',
    tags: ['hubungan', 'self-concept', 'manifestasi'],
    progress: 28,
    totalSessions: 5,
    nextSession: '2026-06-02T16:00:00Z',
    lastSessionAt: '2026-05-26T16:00:00Z',
    goalFocusArea: 'Pasangan',
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-05-26T16:00:00Z',
  },
  {
    id: 'demo-8',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Nadia Fitriani',
    email: 'nadia@email.com',
    whatsapp: '+62812345008',
    status: 'active',
    phase: 'SATS',
    goal: 'Manifestasi pekerjaan remote di perusahaan tech internasional',
    bio: 'Developer 26 tahun yang ingin bekerja dari mana saja. Targetnya dapat posisi senior di startup Silicon Valley dengan gaji USD 150K.',
    tags: ['karir', 'remote-work', 'SATS'],
    progress: 48,
    totalSessions: 8,
    nextSession: '2026-06-03T10:00:00Z',
    lastSessionAt: '2026-05-28T10:00:00Z',
    goalFocusArea: 'Karir',
    createdAt: '2026-03-10T08:00:00Z',
    updatedAt: '2026-05-28T10:00:00Z',
  },
  {
    id: 'demo-9',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Ahmad Fauzi',
    email: 'ahmad@email.com',
    whatsapp: '+62812345009',
    status: 'on_progress',
    phase: 'Progress',
    goal: 'Menarik kesembuhan total dari penyakit autoimun',
    bio: 'Pria 42 tahun yang didiagnosa penyakit autoimun 2 tahun lalu. Sudah dalam proses pemulihan dan ingin mempercepat dengan mindset healing.',
    tags: ['kesehatan', 'healing', 'progress'],
    progress: 70,
    totalSessions: 14,
    nextSession: '2026-06-01T08:00:00Z',
    lastSessionAt: '2026-05-29T08:00:00Z',
    goalFocusArea: 'Kesehatan',
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-05-29T08:00:00Z',
  },
  {
    id: 'demo-10',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Lina Kusuma',
    email: 'lina@email.com',
    whatsapp: '+62812345010',
    status: 'active',
    phase: 'Living End',
    goal: 'Manifestasi pernikahan bahagia dengan pasangan yang sudah ada',
    bio: 'Wanita 35 tahun yang sudah menikah 5 tahun tapi hubungan mulai renggang. Ingin memanifestasikan keintiman dan kebahagiaan dalam pernikahannya.',
    tags: ['hubungan', 'pernikahan', 'living-end'],
    progress: 80,
    totalSessions: 11,
    nextSession: '2026-06-04T14:00:00Z',
    lastSessionAt: '2026-05-30T14:00:00Z',
    goalFocusArea: 'Pasangan',
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-05-30T14:00:00Z',
  },
  {
    id: 'demo-11',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Dimas Surya',
    email: 'dimas@email.com',
    whatsapp: '+62812345011',
    status: 'active',
    phase: 'Intake',
    goal: 'Manifestasi kemampuan public speaking dan confidence',
    bio: 'Pria 27 tahun yang sangat introvert dan punya fear of public speaking. Ingin bisa berbicara di depan 1000 orang dengan penuh percaya diri.',
    tags: ['karir', 'confidence', 'public-speaking'],
    progress: 8,
    totalSessions: 1,
    nextSession: '2026-06-07T10:00:00Z',
    lastSessionAt: '2026-05-20T10:00:00Z',
    goalFocusArea: 'Karir',
    createdAt: '2026-05-15T08:00:00Z',
    updatedAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'demo-12',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Ayu Permata',
    email: 'ayu@email.com',
    whatsapp: '+62812345012',
    status: 'active',
    phase: 'Self-Concept',
    goal: 'Menarik kebebasan waktu dan passive income Rp 30 juta/bulan',
    bio: 'Content creator yang sudah punya 100K followers tapi belum bisa monetize dengan baik. Ingin membangun sistem passive income.',
    tags: ['finansial', 'passive-income', 'content-creator'],
    progress: 32,
    totalSessions: 4,
    nextSession: '2026-06-05T11:00:00Z',
    lastSessionAt: '2026-05-25T11:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2026-04-05T08:00:00Z',
    updatedAt: '2026-05-25T11:00:00Z',
  },
  {
    id: 'demo-13',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Fajar Nugroho',
    email: 'fajar@email.com',
    whatsapp: '+62812345013',
    status: 'completed',
    phase: 'Progress',
    goal: 'Manifestasi rumah impian di kawasan BSD',
    bio: 'Pria 36 tahun yang berhasil mewujudkan impian punya rumah di BSD. Coaching selesai, target tercapai!',
    tags: ['finansial', 'properti', 'sukses'],
    progress: 100,
    totalSessions: 18,
    nextSession: null,
    lastSessionAt: '2026-05-15T09:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2025-11-01T08:00:00Z',
    updatedAt: '2026-05-15T09:00:00Z',
  },
  {
    id: 'demo-14',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Citra Melati',
    email: 'citra@email.com',
    whatsapp: '+62812345014',
    status: 'inactive',
    phase: 'Intake',
    goal: 'Manifestasi travel keliling dunia',
    bio: 'Wanita 25 tahun yang punya impian traveling. Saat ini sedang fokus ke hal lain dan tidak aktif coaching.',
    tags: ['travel', 'lifestyle'],
    progress: 5,
    totalSessions: 1,
    nextSession: null,
    lastSessionAt: '2026-04-10T10:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2026-04-01T08:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'demo-15',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Hendra Saputra',
    email: 'hendra@email.com',
    whatsapp: '+62812345015',
    status: 'active',
    phase: 'SATS',
    goal: 'Menarik body ideal dan lari marathon pertama',
    bio: 'Pria 33 tahun yang ingin transformasi tubuh total. Target: berat badan turun 20kg dan bisa lari marathon 42km.',
    tags: ['kesehatan', 'fitness', 'marathon'],
    progress: 45,
    totalSessions: 7,
    nextSession: '2026-06-02T07:00:00Z',
    lastSessionAt: '2026-05-27T07:00:00Z',
    goalFocusArea: 'Kesehatan',
    createdAt: '2026-03-15T07:00:00Z',
    updatedAt: '2026-05-27T07:00:00Z',
  },
  {
    id: 'demo-16',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Ratna Dewi',
    email: 'ratna@email.com',
    whatsapp: '+62812345016',
    status: 'active',
    phase: 'Living End',
    goal: 'Manifestasi hubungan yang harmonis dengan keluarga besar',
    bio: 'Wanita 40 tahun yang punya konflik keluarga yang berkepanjangan. Ingin mewujudkan keharmonisan dan kedamaian dalam keluarga.',
    tags: ['hubungan', 'keluarga', 'healing'],
    progress: 72,
    totalSessions: 10,
    nextSession: '2026-06-03T16:00:00Z',
    lastSessionAt: '2026-05-29T16:00:00Z',
    goalFocusArea: 'Pasangan',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-05-29T16:00:00Z',
  },
  {
    id: 'demo-17',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Yoga Aditya',
    email: 'yoga@email.com',
    whatsapp: '+62812345017',
    status: 'active',
    phase: 'Progress',
    goal: 'Menarik investasi Rp 5 Miliar untuk startup-nya',
    bio: 'Founder startup edtech yang sudah punya 50K users. Membutuhkan funding series A untuk scale up.',
    tags: ['bisnis', 'startup', 'investasi'],
    progress: 60,
    totalSessions: 8,
    nextSession: '2026-06-06T09:00:00Z',
    lastSessionAt: '2026-05-30T09:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-30T09:00:00Z',
  },
  {
    id: 'demo-18',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Indah Sari',
    email: 'indah@email.com',
    whatsapp: '+62812345018',
    status: 'active',
    phase: 'Self-Concept',
    goal: 'Membangun self-worth dan keluar dari toxic relationship',
    bio: 'Wanita 29 tahun yang baru keluar dari hubungan toxic. Ingin membangun kembali self-worth dan menarik hubungan yang sehat.',
    tags: ['self-love', 'healing', 'hubungan'],
    progress: 25,
    totalSessions: 4,
    nextSession: '2026-06-04T13:00:00Z',
    lastSessionAt: '2026-05-26T13:00:00Z',
    goalFocusArea: 'Pasangan',
    createdAt: '2026-04-25T09:00:00Z',
    updatedAt: '2026-05-26T13:00:00Z',
  },
  {
    id: 'demo-19',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Bagus Setiawan',
    email: 'bagus@email.com',
    whatsapp: '+62812345019',
    status: 'inactive',
    phase: 'Intake',
    goal: 'Menarik karir di industri musik',
    bio: 'Musisi independen yang ingin menembus industri musik mainstream. Sedang hiatus dari coaching.',
    tags: ['karir', 'musik', 'kreatif'],
    progress: 12,
    totalSessions: 2,
    nextSession: null,
    lastSessionAt: '2026-03-20T11:00:00Z',
    goalFocusArea: 'Karir',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-20T11:00:00Z',
  },
  {
    id: 'demo-20',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Putri Handayani',
    email: 'putri@email.com',
    whatsapp: '+62812345020',
    status: 'active',
    phase: 'SATS',
    goal: 'Manifestasi kemampuan menulis buku bestseller',
    bio: 'Penulis freelance yang ingin menulis buku self-help yang menjadi bestseller nasional. Sudah punya draft tapi belum berani publish.',
    tags: ['karir', 'menulis', 'kreatif'],
    progress: 42,
    totalSessions: 6,
    nextSession: '2026-06-05T15:00:00Z',
    lastSessionAt: '2026-05-28T15:00:00Z',
    goalFocusArea: 'Karir',
    createdAt: '2026-03-25T08:00:00Z',
    updatedAt: '2026-05-28T15:00:00Z',
  },
  {
    id: 'demo-21',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Agus Prasetyo',
    email: 'agus@email.com',
    whatsapp: '+62812345021',
    status: 'active',
    phase: 'Living End',
    goal: 'Manifestasi kebebasan waktu untuk keluarga',
    bio: 'Pria 40 tahun, eksekutif sibuk yang jarang bertemu keluarga. Ingin sistem bisnis yang berjalan tanpa dia sehingga bisa quality time.',
    tags: ['keluarga', 'freedom', 'bisnis'],
    progress: 88,
    totalSessions: 16,
    nextSession: '2026-06-02T08:00:00Z',
    lastSessionAt: '2026-05-30T08:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2025-12-01T08:00:00Z',
    updatedAt: '2026-05-30T08:00:00Z',
  },
  {
    id: 'demo-22',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Wulan Dari',
    email: 'wulan@email.com',
    whatsapp: '+62812345022',
    status: 'active',
    phase: 'Progress',
    goal: 'Menarik ketenangan mental dan bebas dari anxiety',
    bio: 'Wanita 31 tahun yang mengalami anxiety berat. Ingin menggunakan teknik manifestasi dan mindfulness untuk healing.',
    tags: ['kesehatan', 'mental', 'healing'],
    progress: 65,
    totalSessions: 11,
    nextSession: '2026-06-03T12:00:00Z',
    lastSessionAt: '2026-05-29T12:00:00Z',
    goalFocusArea: 'Kesehatan',
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-05-29T12:00:00Z',
  },
  {
    id: 'demo-23',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Taufik Rahman',
    email: 'taufik@email.com',
    whatsapp: '+62812345023',
    status: 'active',
    phase: 'Self-Concept',
    goal: 'Menarik kontrak kerja di luar negeri (Jepang)',
    bio: 'Engineer 29 tahun yang impian kerja di Jepang. Sudah belajar bahasa dan punya kualifikasi tapi belum dapet opportunity.',
    tags: ['karir', 'internasional', 'jepang'],
    progress: 30,
    totalSessions: 5,
    nextSession: '2026-06-06T10:00:00Z',
    lastSessionAt: '2026-05-27T10:00:00Z',
    goalFocusArea: 'Karir',
    createdAt: '2026-04-10T08:00:00Z',
    updatedAt: '2026-05-27T10:00:00Z',
  },
  {
    id: 'demo-24',
    orgId: 'demo-org',
    coachId: 'demo-coach',
    name: 'Mega Safitri',
    email: 'mega@email.com',
    whatsapp: '+62812345024',
    status: 'completed',
    phase: 'Progress',
    goal: 'Manifestasi rumah sakit kecantikan sendiri',
    bio: 'Dokter kulit yang berhasil mewujudkan impian punya klinik kecantikan sendiri. Target tercapai setelah 6 bulan coaching!',
    tags: ['bisnis', 'klinik', 'sukses'],
    progress: 100,
    totalSessions: 20,
    nextSession: null,
    lastSessionAt: '2026-05-10T09:00:00Z',
    goalFocusArea: 'Keuangan',
    createdAt: '2025-11-15T08:00:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
  },
];

// ─── Demo Analytics ───
export function getDemoStats() {
  const total = DEMO_CLIENTS.length;
  const active = DEMO_CLIENTS.filter(c => c.status === 'active').length;
  const onProgress = DEMO_CLIENTS.filter(c => c.status === 'on_progress').length;
  const completed = DEMO_CLIENTS.filter(c => c.status === 'completed').length;
  const inactive = DEMO_CLIENTS.filter(c => c.status === 'inactive').length;
  const totalSessions = DEMO_CLIENTS.reduce((sum, c) => sum + c.totalSessions, 0);
  const avgProgress = Math.round(DEMO_CLIENTS.reduce((sum, c) => sum + c.progress, 0) / total);

  return {
    total,
    active: active + onProgress,
    onProgress,
    completed,
    inactive,
    totalSessions,
    avgProgress,
  };
}

// ─── Demo Phase Distribution ───
export function getDemoPhaseDistribution() {
  const phaseMap = new Map<string, number>();
  DEMO_CLIENTS.forEach(c => {
    const count = phaseMap.get(c.phase) || 0;
    phaseMap.set(c.phase, count + 1);
  });
  return Array.from(phaseMap.entries()).map(([name, value]) => ({ name, value }));
}

// ─── Demo Sessions for a Client ───
export function getDemoSessions(clientId: string): Session[] {
  const client = DEMO_CLIENTS.find(c => c.id === clientId);
  if (!client) return [];

  const baseDate = new Date('2026-05-01');
  const sessions: Session[] = [];

  for (let i = 0; i < Math.min(client.totalSessions, 5); i++) {
    const date = new Date(baseDate);
    date.setDate(date.getDate() + (i * 7));
    sessions.push({
      id: `session-${clientId}-${i}`,
      clientId,
      type: ['coaching', 'meditation', 'sats-session', 'check-in', 'breakthrough'][i % 5],
      title: [`Sesi Coaching #${i + 1}`, 'Meditasi Panduan', 'Sesi SATS Intensif', 'Check-in Mingguan', 'Breakthrough Session'][i % 5],
      date: date.toISOString(),
      duration: [60, 45, 30, 15, 90][i % 5],
      notes: `Catatan sesi ${i + 1}: Progress baik, klien menunjukkan tanda-tanda positif dalam proses manifestasi. Terjadi beberapa shift mindset yang signifikan.`,
      summary: `Sesi berjalan sangat baik. Klien semakin memahami konsep manifestasi dan mulai mengaplikasikannya dalam kehidupan sehari-hari.`,
      actionItems: [
        'Praktikkan affirmasi setiap pagi dan malam',
        'Tulis jurnal gratitude sebelum tidur',
        'Lakukan visualisasi 5 menit setelah bangun tidur',
      ],
      mood: ['excellent', 'good', 'neutral', 'good', 'excellent'][i % 5],
      insights: [
        'Klien mulai memahami bahwa perasaan lebih penting dari pikiran',
        'Ada kemajuan dalam self-awareness dan pengenalan limiting beliefs',
        'Energy klien lebih positif dibanding sesi sebelumnya',
      ],
      createdAt: date.toISOString(),
      updatedAt: date.toISOString(),
    });
  }
  return sessions;
}

// ─── Demo Goals for a Client ───
export function getDemoGoals(clientId: string): ClientGoal[] {
  const client = DEMO_CLIENTS.find(c => c.id === clientId);
  if (!client) return [];

  return [
    {
      id: `goal-${clientId}-1`,
      clientId,
      title: client.goal || 'Tujuan Utama',
      description: `Tujuan utama coaching: ${client.goal}`,
      targetDate: '2026-12-31',
      progress: client.progress,
      status: client.progress >= 100 ? 'completed' : 'active',
      category: client.goalFocusArea,
      milestones: [
        { title: 'Menyelesaikan fase Intake', completed: client.progress > 10, date: '2026-05-15' },
        { title: 'Membangun Self-Concept baru', completed: client.progress > 30, date: '2026-06-15' },
        { title: 'Menguasai teknik SATS', completed: client.progress > 50, date: '2026-07-15' },
        { title: 'Living in the End secara konsisten', completed: client.progress > 70, date: '2026-08-15' },
        { title: 'Tujuan termanifestasi', completed: client.progress >= 100, date: '2026-12-31' },
      ],
      createdAt: client.createdAt,
      updatedAt: client.updatedAt,
    },
  ];
}

// ─── Demo Notes for a Client ───
export function getDemoNotes(clientId: string): ClientNote[] {
  const client = DEMO_CLIENTS.find(c => c.id === clientId);
  if (!client) return [];

  return [
    {
      id: `note-${clientId}-1`,
      clientId,
      content: `Klien menunjukkan antusiasme tinggi dalam proses coaching. Ada kemauan kuat untuk berubah dan pertumbuhan yang konsisten dari sesi ke sesi.`,
      type: 'insight',
      isPinned: true,
      createdAt: client.createdAt,
      updatedAt: client.updatedAt,
    },
    {
      id: `note-${clientId}-2`,
      clientId,
      content: `Limiting belief utama: "${client.goal ? 'Saya tidak cukup baik untuk mencapai ini' : 'Saya tidak pantas sukses'}" — perlu di-reframe di sesi berikutnya.`,
      type: 'block',
      isPinned: false,
      createdAt: client.createdAt,
      updatedAt: client.updatedAt,
    },
    {
      id: `note-${clientId}-3`,
      clientId,
      content: `Affirmasi personal: "Saya layak menerima semua kebaikan yang alam semesta tawarkan. Setiap hari saya semakin dekat dengan tujuan saya."`,
      type: 'affirmation',
      isPinned: true,
      createdAt: client.createdAt,
      updatedAt: client.updatedAt,
    },
  ];
}

// ─── Upcoming Sessions (across all demo clients) ───
export function getDemoUpcomingSessions() {
  return DEMO_CLIENTS
    .filter(c => c.nextSession && c.status !== 'inactive' && c.status !== 'completed')
    .map(c => ({
      id: `upcoming-${c.id}`,
      clientName: c.name,
      clientId: c.id,
      date: c.nextSession!,
      type: 'Sesi Coaching',
      phase: c.phase,
    }))
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
    .slice(0, 5);
}

// ─── Demo Recent Activity ───
export function getDemoRecentActivity() {
  return [
    { id: '1', type: 'achievement' as const, title: 'Fajar Nugroho berhasil manifestasi rumah!', description: 'Setelah 18 sesi coaching, target rumah di BSD akhirnya tercapai.', time: '2 jam lalu', clientName: 'Fajar Nugroho' },
    { id: '2', type: 'milestone' as const, title: 'Andi Wijaya masuk fase Living End', description: 'Progress mencapai 75%, klien siap untuk teknik Living in the End.', time: '5 jam lalu', clientName: 'Andi Wijaya' },
    { id: '3', type: 'insight' as const, title: 'AI Insight: Pola baru terdeteksi', description: '3 klien menunjukkan pola limiting belief yang sama tentang uang. Pertimbangkan sesi group coaching.', time: '1 hari lalu', clientName: 'Sistem AI' },
    { id: '4', type: 'achievement' as const, title: 'Mega Safitri buka klinik kecantikan!', description: 'Setelah 20 sesi, impian punya klinik kecantikan akhirnya terwujud.', time: '3 hari lalu', clientName: 'Mega Safitri' },
    { id: '5', type: 'warning' as const, title: 'Citra Melati tidak aktif 50 hari', description: 'Klien tidak respons sejak 10 April. Perlu follow-up via WhatsApp.', time: '1 minggu lalu', clientName: 'Citra Melati' },
  ];
}

// ─── Check if Demo Mode ───
export function isDemoMode(): boolean {
  if (typeof window === 'undefined') return false;
  return !localStorage.getItem('coachflo_auth_token');
}
